version: "3.3"

services:
  telegraf:
    image: telegraf:1.9.3
    networks:
      - outside
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: telegraf-config
        target: /etc/telegraf/telegraf.conf
    deploy:
      mode: global

  influxdb:
    image: influxdb:1.7.3
    ports:
      - "8086:8086"
    networks:
      - tig-net
    deploy:
      placement:
        constraints:
          - node.labels.db == true
          - node.labels.arch == x86

  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - "3000:3000"
    networks:
      - tig-net
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.labels.arch == x86
        preferences:
          - spread: node.labels.datacenter

configs:
  telegraf-config:
    file: $PWD/conf/telegraf/telegraf.conf

networks:
  tig-net:
    driver: overlay
  outside:
    external:
      name: "host"
