version: "3.3"

services:
  telegraf:
    image: telegraf:1.9.3
    networks:
      - outside
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: telegraf-config
        target: /etc/telegraf/telegraf.conf
    deploy:
      restart_policy:
        condition: on-failure
      mode: global

  influxdb:
    image: influxdb:1.7.3
    networks:
      - outside
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - "3000:3000"
    networks:
      - outside
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

configs:
  telegraf-config:
    file: $PWD/conf/telegraf/telegraf.conf

networks:
  tig-net:
    driver: overlay
  outside:
    external:
      name: "host"
